### PR TITLE
new package: rxvt-unicode

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by konimex** [comment]
Please move it to `public`.

**Comment by dylanaraps** [comment]
Is there a point to the `.desktop` file if we won't have any Desktop Environments packaged? Are they used elsewhere by anything else?

**Comment by dylanaraps** [comment]
If `perl` is enabled in the build should it not then be a runtime dependency? Does URxvt work fine afterwards if `perl` is removed?

**Comment by dylanaraps** [comment]
I would also prefer we didn't store any binary data in this repository (talking specifically about the `.png` file). Why is it needed?

**Comment by shizonic** [comment]
> Is there a point to the `.desktop` file if we won't have any Desktop Environments packaged? Are they used elsewhere by anything else?

No. Will remove it asap.

**Comment by shizonic** [comment]
> If `perl` is enabled in the build should it not then be a runtime dependency? Does URxvt work fine afterwards if `perl` is removed?

Absolutely correct. Will ad it as runtime dep asap.

**Comment by shizonic** [comment]
> I would also prefer we didn't store any binary data in this repository (talking specifically about the `.png` file). Why is it needed?

No. Will remove it too asap.

**Comment by dylanaraps** [comment]
LGTM :+1:

**Pull request merged**
